
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                # - not_null
                # - accepted_values:
                    # values: [1, 2, 3]  # only accept these values
                    # quote: false

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                - relationships:
                    to: ref('my_first_dbt_model')
                    field: id

    - name: snowflake_customer_purchases
      description: "the total purchases for each customer in snowflake sample data"
      columns:
        - name: c_custkey
          tests:
            - unique
            - not_null

    - name: snowflake_accumulate_purchases
      description: "the total purchases accumulated by day"
      columns:
        - name: date
          tests:
            - not_null
    
    - name: incremental_time
      description: 'dim time'
      columns:
        - name: t_time
          tests:
            - unique
            - not_null

    - name: playing_with_tests
      description: 'custom test assignment'
      columns:
        - name: c_custkey
          tests:
            - unique
            - not_null

sources:
  - name: sample_data_sf1
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: c_mktsegment
        tests:
          - accepted_values:
              values: ['BUILDING','AUTOMOBILE','HOUSEHOLD','FURNITURE','MACHINERY']
      - name: orders

  - name: sample_data_sf001
    database: snowflake_sample_data
    schema: tpch_sf001
    tables:
      - name: customer